services:
  - type: web
    name: anish-code
    env: node
    plan: free
    buildCommand: npm install --omit=dev && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: anish-code-db
          property: connectionString
      - key: SESSION_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false
databases:
  - name: anish-code-db
    plan: free
